### ISSUE TITLE
Failed initialising Tizen appium server

### ISSUE THREAD

**Issue by BoazWarshawsky** [Samsung/appium-tizen-driver#16]
I fails connecting to appium server and start the test, see attached log.
My script looks as follow:
`var appiumTizenDriver = require("appium-tizen-driver");`

`defaultCaps = {`
`    appPackage: '62c6AU3M4C',`
`    deviceName: 'Tizen',`
`    platformName: 'Tizen'`
`}`
`var driver = new appiumTizenDriver.TizenDriver()`

`driver.createSession(defaultCaps);`

I see in the log the following:
ERR! SDB Error: Error finding if app is installed. Original error: Error executing sdbExec. Original error: 'Command '/Users/boazwarshawsky/tizen-studio/tools/sdb -s 192.168.70.85\:26101 shell 'app_launcher --list | grep 62c6AU3M4C'' exited with code 1'; Stderr: 'closed'; Code: '1'
E

**Comment by BoazWarshawsky** [comment]
Full error log:
dbug BaseDriver Creating session with MJSONWP desired capabilities: {"appPackage":"62c6AU3M4C",...
info BaseDriver Session created with session id: 085e2a4c-65dc-4b49-ad3a-7269754006d7
boaz
info SDB Using sdb from /Users/boazwarshawsky/tizen-studio/tools/sdb
info SDB 
info TizenDriver Retrieving device list
dbug SDB Trying to find a connected tizen device
dbug SDB Getting connected devices...
dbug SDB 1 device(s) connected
info TizenDriver Using device: 192.168.70.85:26101
info SDB Using sdb from /Users/boazwarshawsky/tizen-studio/tools/sdb
info SDB 
dbug SDB Setting device id to 192.168.70.85:26101
dbug SDB Getting install status for 62c6AU3M4C
dbug SDB Running '/Users/boazwarshawsky/tizen-studio/tools/sdb' with args: ["-s","192.168.70.85:26101","shell","app_launcher --list | grep 62c6AU3M4C"]
dbug SDB Running '/Users/boazwarshawsky/tizen-studio/tools/sdb' with args: ["-s","192.168.70.85:26101","shell","app_launcher --list | grep 62c6AU3M4C"]
ERR! SDB Error: Error finding if app is installed. Original error: Error executing sdbExec. Original error: 'Command '/Users/boazwarshawsky/tizen-studio/tools/sdb -s 192.168.70.85\:26101 shell 'app_launcher --list | grep 62c6AU3M4C'' exited with code 1'; Stderr: 'closed'; Code: '1'
ERR! SDB     at Object.wrappedLogger.errorAndThrow (/Users/boazwarshawsky/workspace/VisualStudioCode/samsung_tv_automation/node_modules/appium-support/lib/logging.js:78:13)
ERR! SDB     at SDB.callee$0$0$ (/Users/boazwarshawsky/workspace/VisualStudioCode/samsung_tv_automation/node_modules/appium-sdb/lib/tools/tpk-utils.js:16:9)
ERR! SDB     at tryCatch (/Users/boazwarshawsky/workspace/VisualStudioCode/samsung_tv_automation/node_modules/babel-runtime/regenerator/runtime.js:67:40)
ERR! SDB     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/boazwarshawsky/workspace/VisualStudioCode/samsung_tv_automation/node_modules/babel-runtime/regenerator/runtime.js:315:22)
ERR! SDB     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/boazwarshawsky/workspace/VisualStudioCode/samsung_tv_automation/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! SDB     at GeneratorFunctionPrototype.invoke (/Users/boazwarshawsky/workspace/VisualStudioCode/samsung_tv_automation/node_modules/babel-runtime/regenerator/runtime.js:136:37)
ERR! SDB     at <anonymous>
dbug TizenDriver Shutting down Tizen driver
dbug TizenDriver Called deleteSession but bootstrap wasn't active
(node:24990) UnhandledPromiseRejectionWarning: Error: Error finding if app is installed. Original error: Error executing sdbExec. Original error: 'Command '/Users/boazwarshawsky/tizen-studio/tools/sdb -s 192.168.70.85\:26101 shell 'app_launcher --list | grep 62c6AU3M4C'' exited with code 1'; Stderr: 'closed'; Code: '1'
    at Object.wrappedLogger.errorAndThrow (/Users/boazwarshawsky/workspace/VisualStudioCode/samsung_tv_automation/node_modules/appium-support/lib/logging.js:78:13)
    at SDB.callee$0$0$ (/Users/boazwarshawsky/workspace/VisualStudioCode/samsung_tv_automation/node_modules/appium-sdb/lib/tools/tpk-utils.js:16:9)
    at tryCatch (/Users/boazwarshawsky/workspace/VisualStudioCode/samsung_tv_automation/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/boazwarshawsky/workspace/VisualStudioCode/samsung_tv_automation/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/boazwarshawsky/workspace/VisualStudioCode/samsung_tv_automation/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/boazwarshawsky/workspace/VisualStudioCode/samsung_tv_automation/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
(node:24990) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24990) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BoazWarshawsky** [comment]
I am getting the same error when the desiCab defined as follow:
defaultCaps = {
    appPackage: '62c6AU3M4C',
    deviceName: 'UE49UN8000',
    platformName: 'Tizen'
}

**Comment by BoazWarshawsky** [comment]
Also tried running the script as follow:
`let appiumTizenDriver = require("appium-tizen-driver");`
`let defaultCaps = {`
`    appPackage: '62c6AU3M4C',`
`    deviceName: 'UE49UN8000',`
`    platformName: 'Tizen'`
`}`
`var driver = new appiumTizenDriver.TizenDriver();`
`driver.createSession(defaultCaps)`

**Comment by BoazWarshawsky** [comment]
@imurchie @Seo-Young , can you help with that?

**Comment by imurchie** [comment]
I have no access to a device, and no particular knowledge of how this works, unfortunately. I will be of no help.

**Comment by BoazWarshawsky** [comment]
thanks @imurchie, if anyone else can help here that would be appreciated.

**Comment by BoazWarshawsky** [comment]
Hi, 
I am now noticing that the `appium-tizen-driver` is for .NET Samsung TV application, and the application that I am trying to automate is Samsung Web Application,

Does it should still work for me?

**Comment by flyofsky** [comment]
The issue at the moment is that `sdb` is blocked to public on TV.
`sdb` connects to devices similar to `adb`.
Now TV does not support sdb due to security policy.
Please note that it works with Tizen Mobile emulator and Tizen wearables(Tizen 4.0 or above).

**Comment by anushachavan** [comment]
ERR! SDB Error: Error finding if app is installed. Original error: Error executing sdbExec. Original error: 'Command '/Users/boazwarshawsky/tizen-studio/tools/sdb -s 192.168.70.85:26101 shell 'app_launcher --list | grep 62c6AU3M4C'' exited with code 1'; Stderr: 'closed'; Code: '1'

We observe this issue while trying to launch app from Appium capabilities set on Samsung Tizen TV. Can anyone help us here to resolve this issue.
